export enum LanguageISO6391Enum {
  Russian = 'ru',
  English = 'en',
  Spanish = 'es',
  French = 'fr',
  Italian = 'it',
  German = 'de',
  Portuguese = 'pt',
  Dutch = 'nl',
  Swedish = 'sv',
  Norwegian = 'no',
  Danish = 'da',
  Romanian = 'ro',
  Catalan = 'ca',
  Hungarian = 'hu',
  Finnish = 'fi',
  Turkish = 'tr',
}
